apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: app
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo LOG_LEVEL=$LOG_LEVEL PASSWORD=$PASSWORD && sleep 3600",
        ]
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
