# Topic 10: Jobs & CronJobs
# Job: run to completion. CronJob: scheduled Jobs.
#
# Apply: kubectl apply -f .

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 1 #Run 1 Pod in total
  parallelism: 1 # Run 1 pod at a time
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["echo", "Job completed"]
      restartPolicy: OnFailure
