# Topic 3: Services
# ClusterIP (default), NodePort, LoadBalancer
#
# Apply: kubectl apply -f .
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
